---
title       : 
subtitle    : 
author      : 
job         : 
framework   : impressjs        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

```{r results='hide', echo=FALSE, warning=FALSE, message=FALSE}
library(WindR)
w.start()
require(quantmod)
library(ggplot2)
library(reshape2)
```


```{r warning=FALSE, echo=FALSE, results='hide', message=FALSE}
options(width = 80, scipen = 6, digits = 3)
options(replace.assign = TRUE)
pdf.options(family='GB1')
```

```{r echo=FALSE, warning=FALSE}
#################################################################
## -> Initialization
#################################################################
## library(WindR)
## w.start()
ticker <- c("300020")    ## 银江股份
source("G:/国信证券/工作日志/R-scripts/WindRPlot.R")
#################################################################
## <- Initialization
#################################################################
```

--- #intro1 x:500 y:500 z:0 rotx:90 roty:90
```{r  echo=FALSE, warning=FALSE}

stock.daily.plot("000001.SH")
```


--- #intro113 x:10000  

```{r  echo=FALSE, warning=FALSE}
### TradeDate:
#TradeDate <- as.Date(Sys.Date(), format="%y%m%d")
#TradeDate <- paste(substr(TradeDate,1,4), substr(TradeDate,6,7), substr(TradeDate,9,10), sep="")
### SSEC：上证综合指数
##
## Return.Compare("000977", "884091")
Return.Compare <- function(ticker, Ind.Index, from="2014-11-01", to=Sys.Date()){
  ## 上证指数：000001.SH
  #SSEC <- w.wsd("000001.SH","open,high,low,close,volume", from, to, "adjDate=0;ndays=5;Fill=Previous;priceAdj=B")
  #SSEC <- xts(SSEC$Data[,-1], SSEC$Data[,1])
  ## 沪深300：000300.SH
  Market.Index <- c("000001.SH")
  Market.inf <- w.wss(Market.Index,'sec_name')
  Market.name <- paste(Market.inf$Data$SEC_NAME)
  Market.Index <- w.wsd("000001.SH","open,high,low,close,volume", from, to, "adjDate=0;ndays=5;Fill=Previous;priceAdj=B")
  Market.Index <- xts(Market.Index$Data[,-1], Market.Index$Data[,1])
  ## 板块指数
  Ind.Index <- paste(substr(Ind.Index,1,6), ".WI", sep="")
  Ind.inf <- w.wss(Ind.Index,'sec_name')
  Ind.name <- paste(Ind.inf$Data$SEC_NAME)
  Ind.Index <- w.wsd(Ind.Index,"open,high,low,close,volume", from, to, "adjDate=0;ndays=5;Fill=Previous;priceAdj=B")
  Ind.Index <- xts(Ind.Index$Data[,-1], Ind.Index$Data[,1]) 
  ## 股票收益率
  STOCK.CODE.WindR <- function(ticker){
    if(substr(ticker, 1, 1) == 0|3)
      TICKER <- paste(substr(ticker, 1, 6),".SZ", sep="")
    if(substr(ticker, 1, 1) == 6)
      TICKER <- paste(substr(ticker, 1, 6),".SH", sep="")
    return(TICKER)
  }
  ##
  ticker.Comp <- STOCK.CODE.WindR(ticker)
  Sec.inf <- w.wss(ticker.Comp,'sec_name')
  #stock.name <- paste(Sec.inf$Data$SEC_NAME,Sec.inf$Data$CODE, sep=" ")
  stock.name <- paste(Sec.inf$Data$SEC_NAME)
  ticker.Comp <- w.wsd(ticker.Comp,"open,high,low,close,volume",from, to,"adjDate=0;ndays=5;Fill=Previous;priceAdj=B")
  ticker.Comp <- ticker.Comp$Data
  ticker.Comp <- xts(ticker.Comp[,-1], ticker.Comp[,1]) 
  ## Plotting
  ind <- function(x) {
    # Divide each column by the first non-NA value
    # (There may already be a function to do that.)
    coredata(x) <- t(t(coredata(x)) / apply(coredata(x),2,function(u){ c(u[!is.na(u)&u!=0],NA)[1] }))
    x
  }
  x <- cbind(Market.Index[,4], Ind.Index[,4], ticker.Comp[,4])
  library(reshape2)
  d <- data.frame( date = index(x), coredata(ind(x)) )
  names(d) = c("日期",Market.name, Ind.name, stock.name)
  # names(d) <- gsub("\\..*", "", names(d))
  d <- melt(d, id.vars="日期")
  names(d) = c("日期","指数","收益率")
  ggplot(d, aes(日期, 收益率, color=指数)) + geom_line(size=1.4) 
}

Return.Compare("300033", "884136")
```

---.slide #intro12 x:1000 y:4500 z:-3500 rotx:90 roty:90
## 发展契机
### 提高城镇化质量治疗“城市病” 
#### 新型城市化发展模式

### 聚集新兴产业转变发展方式 
#### 工业化 ==> 自动化 ==> 信息化化 ==> 智能化

### 均化公共服务改善民生保障 
#### “治大国若烹小鲜”

---.slide #intro13 x:1000 y:5500 z:-3500 rotx:90 roty:90
```{r}
x = rnorm(1000)
plot.ts(x)
```




